"""Generate docs/mcp-tool-catalog.md from the live FastMCP tool registry."""

from __future__ import annotations

import argparse
import asyncio
import difflib
from collections import defaultdict
from pathlib import Path
from typing import Any

from app.main import mcp

REPO_ROOT = Path(__file__).resolve().parents[3]
CATALOG_PATH = REPO_ROOT / "docs" / "mcp-tool-catalog.md"


def _clean_markdown_cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _schema_type(schema: dict[str, Any]) -> str:
    if "type" in schema:
        type_value = schema["type"]
        if isinstance(type_value, list):
            return " | ".join(str(part) for part in type_value)
        return str(type_value)
    if "anyOf" in schema:
        return " | ".join(_schema_type(part) for part in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(_schema_type(part) for part in schema["oneOf"])
    if "$ref" in schema:
        return str(schema["$ref"])
    return "unknown"


def _render_param_table(parameters: dict[str, Any]) -> str:
    properties: dict[str, dict[str, Any]] = parameters.get("properties", {})
    required = set(parameters.get("required", []))
    if not properties:
        return "_No input parameters._"

    lines = [
        "| name | type | required | description |",
        "|---|---|---|---|",
    ]
    for name in sorted(properties):
        schema = properties[name]
        lines.append(
            "| "
            f"`{name}` | `{_schema_type(schema)}` | "
            f"{'yes' if name in required else 'no'} | "
            f"{_clean_markdown_cell(schema.get('description') or '')} |"
        )
    return "\n".join(lines)


async def _generate() -> str:
    tool_groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for tool in await mcp.list_tools():
        raw_name = tool.name
        if "_" not in raw_name:
            continue
        namespace, local_name = raw_name.split("_", 1)
        if local_name == "ping":
            continue
        dumped = tool.model_dump(by_alias=True)
        tool_groups[namespace].append(
            {
                "name": local_name,
                "description": (dumped.get("description") or "").strip(),
                "parameters": dumped.get("parameters") or {},
            }
        )

    lines = [
        "# MCP tool catalog",
        "",
        "<!-- Auto-generated by apps/mcp/scripts/gen_tool_catalog.py; do not edit by hand. -->",
        "",
    ]
    ordered_namespaces = sorted(tool_groups, key=lambda ns: (ns != "schema", ns))
    for namespace in ordered_namespaces:
        lines.append(f"## {namespace}")
        lines.append("")
        for tool in sorted(tool_groups[namespace], key=lambda entry: entry["name"]):
            lines.append(f"### {tool['name']}")
            lines.append("")
            if tool["description"]:
                lines.append(_clean_markdown_cell(tool["description"]))
                lines.append("")
            lines.append(_render_param_table(tool["parameters"]))
            lines.append("")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _check_or_write(rendered: str, *, check: bool) -> int:
    current = CATALOG_PATH.read_text(encoding="utf-8") if CATALOG_PATH.exists() else ""
    if check:
        if current == rendered:
            print("docs/mcp-tool-catalog.md is up to date")
            return 0
        diff = "".join(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                rendered.splitlines(keepends=True),
                fromfile="docs/mcp-tool-catalog.md",
                tofile="docs/mcp-tool-catalog.md (generated)",
            )
        )
        print(diff, end="")
        return 1

    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_PATH.write_text(rendered, encoding="utf-8")
    print(f"Updated {CATALOG_PATH.relative_to(REPO_ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if catalog is stale.")
    args = parser.parse_args()
    rendered = asyncio.run(_generate())
    return _check_or_write(rendered, check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
